spring.application.name=consumer-service
app.file.output.dir=./output
app.kafka.topic=test-producer-4
app.file.db-path=./output/rocksdb
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=MANUAL_IMMEDIATE